version: "3.7"
services:
  notifier:
    container_name: test-notifier
    image: guanacoio/notifications:latest
    entrypoint: /go/bin/notifications /etc/notifications/config.yml
    volumes:
      - "./test.yml:/etc/notifications/config.yml"
      - "./test.gohtml:/etc/notifications/test.gohtml"