dry_run: true

alerta:
  endpoint: http://host.docker.internal:8283/api
  webui: http://localhost:8283
  apiToken: ''
  reload_interval: 30

channel_settings:
  smtp:
    server: smtp.example.com
    from: user@example.com
    user: username
    password: 'password'
    ssl: True

  slack:
    webhook_url: 'https://hooks.slack.com/services/1/2/3'

channels:
  marketing:
    type: mail
    config:
      to: user@example.com
      template: "/etc/notifications/test.gohtml"

  mail_support:
    type: mail
    config:
      to: user@example.com, user2@example.com
      template: "/etc/notifications/test.gohtml"

  slack_support:
    type: slack
    config:
      slack_channel: '#test'

rules:
  test:
    filter: status=open&environment=Development
    channels:
      - slack_support
      - mail_support

  marketing_test:
    filter: status=open&environment=Production&service=yourservice
    channels:
      - marketing